name: Run CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Pnpm Install
        uses: ./.github/actions/install-pnpm

      - name: Run CI
        run: pnpm run ci
